// <auto-generated />
namespace Irdata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Volunteer5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Volunteer5));
        
        string IMigrationMetadata.Id
        {
            get { return "201901271712576_Volunteer5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
